//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public int id { get; set; }
        public int Ben_AccNo { get; set; }
        public int User_AccNo { get; set; }
        public string Ben_Name { get; set; }
        public string Ben_NickName { get; set; }
        public string Ben_Banktype { get; set; }
        public string IFSC_code { get; set; }
    
        public virtual User_Details User_Details { get; set; }
    }
}
