//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int id { get; set; }
        public int Acc_No { get; set; }
        public Nullable<System.DateTime> Session_Login { get; set; }
        public Nullable<System.DateTime> Session_Logout { get; set; }
    
        public virtual User_Details User_Details { get; set; }
    }
}
