//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Details()
        {
            this.Beneficiaries = new HashSet<Beneficiary>();
            this.Sessions = new HashSet<Session>();
            this.Transfer_Details_Deposit = new HashSet<Transfer_Details_Deposit>();
            this.Transfer_Details_Withdraw = new HashSet<Transfer_Details_Withdraw>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int Acc_No { get; set; }
        public string Ref_ID { get; set; }
        public string Title { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public long MobNo { get; set; }
        public string Email { get; set; }
        public long Aadhar_No { get; set; }
        public System.DateTime DOB { get; set; }
        public string AddressL1 { get; set; }
        public string AddressL2 { get; set; }
        public string Landmark { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Pincode { get; set; }
        public string P_Address1 { get; set; }
        public string P_Address2 { get; set; }
        public string P_Landmark { get; set; }
        public string P_City { get; set; }
        public string P_State { get; set; }
        public int P_Pincode { get; set; }
        public string OccupationType { get; set; }
        public string Src_Income { get; set; }
        public decimal GrossAnnual_Income { get; set; }
        public string DebitCard { get; set; }
        public string NetBanking { get; set; }
        public string AccountType { get; set; }
        public string Branch_Name { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiary> Beneficiaries { get; set; }
        public virtual IFSC IFSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_Details_Deposit> Transfer_Details_Deposit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer_Details_Withdraw> Transfer_Details_Withdraw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
